### ISSUE TITLE
Weed out crufty definitions and styles

### ISSUE THREAD

**Issue by palewire** [datadesk/osm-quiet-la#29]
Too bad there isn't a nice feature in TileMill to detect these automatically.

**Comment by ldegroot** [comment]
“crufty”?

**Comment by palewire** [comment]
As in, things defined that are no longer used. I suspect (though I could be wrong) that things like the old line casing fills are no longer needed. While I'm in here I figured I'd do a little housekeeping, with virtually all of it stuff I dumped in there lazily in the first place.

**Comment by ldegroot** [comment]
Ah. I meant to do that. Great word though. I’m stealing it.

Len

**Comment by palewire** [comment]
Yeah no biggie. We'll get there eventually but it's not a back breaker. The best tickets are aspirations, I think.
