### ISSUE TITLE
Simplified query and style for roads at middle zoom, like 11-13

### ISSUE THREAD

**Issue by palewire** [datadesk/osm-quiet-la#4]

**Comment by palewire** [comment]
This should attack the exits and overlaps issues identified by @tbone. If he had a screenshot of ones he found particularly offensive that would helpful because we could use it as a target for fix.

**Comment by tbone** [comment]
generally the 12 zoom view, though i think re-arranging layers will clean
that up (or maybe a different styling until you get to 13). here's some
screenshots

**Comment by tbone** [comment]
here's the screen grabs:
![10-rosemead](https://f.cloud.github.com/assets/150045/72957/ba668392-602a-11e2-8e0c-f6e752adce24.png)
![elysian](https://f.cloud.github.com/assets/150045/72958/ba674d5e-602a-11e2-8050-14eabfe9bcd3.png)
![10-710](https://f.cloud.github.com/assets/150045/72959/bae6c638-602a-11e2-9114-e4d304a243fe.png)

**Comment by palewire** [comment]
Thanks dude. Any opinion of the ordering done by HighRoad: https://github.com/migurski/HighRoad

They have a custom PGSQL query against the OpenStreetMap roads database for each zoom level, which gives them more control. We're just using two different queries right now.

**Comment by tbone** [comment]
those results are pretty good. i wonder if they (and we) are outlining the
highways a little soon? they almost have to, since they are using white for
water. just thoughts at this point
